version: 0.2
phases:
  build:
    commands:
      - cd function && npm install && cd ..
      - >
        aws cloudformation package
        --template-file sam.yml
        --s3-bucket ${Bucket}
        --output-template-file packaged.yml
      - echo '{"Parameters" : {' >> config.json
      - echo '"TABLE_NAME": "${TableName}",'>> config.json
      - echo '"TOPIC_ARN": "${TopicArn}"' >> config.json
      - echo '}}' >> config.json
artifacts:
  files:
    - config.json
    - sam.yml
    - packaged.yml
