version: 0.2
phases:
  build:
    commands:
      - >
        aws cloudformation package
        --template-file sam.yml
        --s3-bucket ${Bucket}
        --output-template-file packaged.yml
artifacts:
  files:
    - sam.yml
    - packaged.yml
