version: 0.1
phases:
  build:
    commands:
      - aws cloudformation package --template-file sam.yml      --s3-bucket ${BUCKET} --output-template-file packaged.yaml
      - aws cloudformation deploy  --template-file packaged.yml --stack-name ${STACK_NAME} --capabilities CAPABILITY_IAM
    finally:
      - echo "build app"
artifacts:
  files:
    - appspec.yml
