version: 0.2
phases:
  build:
    commands:
      - cd function && npm install && cd ..
      - >
        aws cloudformation package
        --template-file sam.yml
        --s3-bucket ${Bucket}
        --output-template-file packaged.yml
      - 'echo "{\"Parameters\" : { \"ApiName\": \"${ApiName}\", \"TableName\": \"${TableName}\", \"TopicArn\": \"${TopicArn}\" }}" >> config.json'
artifacts:
  files:
    - config.json
    - sam.yml
    - packaged.yml
