version: 0.1
phases:
  build:
    commands:
      - cd function && zip -r function.zip .
      - >
        aws lambda create-function
        --zip-file fileb://${PWD}.zip
        --runtime nodejs8.10
        --handler index.handler
        --memory-size 128
        --timeout 10
        --function-name testing456
        --description "Contact Form"
        --role arn:aws:iam::655604346524:role/service-role/
      - aws lambda create-alias
    finally:
      - echo "build app"
artifacts:
  files:
    - appspec.yml
