AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Serverless Contact Form

Resources:
  MyAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: my-api
      StageName: prod
      EndpointConfiguration: EDGE
      Cors:
        AllowMethods: "'GET,POST'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
  ContactForm:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: ./function
      Description: >-
        Serverless Contact Form
      MemorySize: 128
      Timeout: 10
      AutoPublishAlias: live
      DeploymentPreference:
        Type: AllAtOnce
      Events:
        Post:
          Type: Api
          Properties:
            Path: /
            Method: Post
            RestApiId:
              Ref: MyAPI
      Policies:
       - AWSLambdaExecute # Managed Policy
       - Version: '2012-10-17' # Policy Document
         Statement:
           - Effect: Allow
             Action:
               - sns:*
               - logs:*
               - cloudwatch:*
             Resource: "*"
