AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Serverless Contact Form
Parameters:
  DynamoDBTableReadCapacityUnits:
    Type: Number
  DynamoDBTableWriteCapacityUnits:
    Type: Number
  TopicDisplayName:
    Type: String
  TopicSubscriptionEmail:
    Type: String
Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: email
          KeyType: HASH
        - AttributeName: created_at
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref DynamoDBTableReadCapacityUnits
        WriteCapacityUnits: !Ref DynamoDBTableWriteCapacityUnits
  Topic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Ref TopicDisplayName
      Subscription:
        - Endpoint: !Ref TopicSubscriptionEmail
          Protocol: email
  MyAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      EndpointConfiguration: EDGE
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
  ContactForm:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs14.x
      CodeUri: ./function
      Description: >-
        Serverless Contact Form
      MemorySize: 128
      Timeout: 10
      AutoPublishAlias: live
      DeploymentPreference:
        Type: AllAtOnce
      Events:
        Post:
          Type: Api
          Properties:
            Path: /
            Method: Post
            RestApiId:
              Ref: MyAPI
      Environment:
        Variables:
          TABLE_NAME: !Ref DynamoDBTable
          TOPIC_ARN:  !GetAtt Topic.Arn
      Policies:
       - AWSLambdaExecute # Managed Policy
       - Version: '2012-10-17' # Policy Document
         Statement:
           - Effect: Allow
             Action:
               - sns:*
               - logs:*
               - cloudwatch:*
               - dynamodb:PutItem
             Resource: "*"
